version: '3'

services:
  nginx:
    container_name: NGINX
    image: nginx:latest
    volumes:
      - /etc/nginx/sites-available:/etc/nginx/sites-available
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/logs:/var/log/nginx
      - /etc/certificados:/etc/certificados
      - /etc/site_prod/keycloak:/var/www/html/site
    ports:
      - 80:80
      - 443:443
    command: bash -c "mkdir -p /etc/nginx/sites-enabled/; ln -s /etc/nginx/sites-available/* /etc/nginx/sites-enabled/; nginx -g 'daemon off;'"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.3
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
     - /etc/keycloak_themes:/opt/keycloak/themes
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - KEYCLOAK_LOGLEVEL=DEBUG
      - KC_DB=mysql
      - KC_DB_URL_HOST=${DB_HOST}
      - KC_DB_URL_PORT=${DB_PORT}
      - KC_DB_URL_DATABASE=${DB_NAME}
      - KC_DB_USERNAME=${DB_USER}
      - KC_DB_PASSWORD=${DB_PASSWORD}
      - KC_HOSTNAME=keycloak.juansalles.com.br
      - KC_PROXY_HEADERS=xforwarded
    command: ["start-dev"]

networks:
  myNetwork:
      