name: Update Docker Compose

on:
  workflow_dispatch:

jobs:
    update:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
      - name: Upload Docker Compose and clear all containers
        run: |
            ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
            scp ./docker/docker-compose.yaml ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }}
            ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'docker rm -f $(docker ps -a -q)'

      - name: SetUp Evironment Variables and Run Docker Compose on host
        run: |
            ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "\
            export KEYCLOAK_USER=${{ secrets.KEYCLOAK_USER }} && \
            export KEYCLOAK_PASSWORD=${{ secrets.KEYCLOAK_PASSWORD }} && \
            export DB_HOST=${{ secrets.DB_HOST }} && \
            export DB_PORT=${{ secrets.DB_PORT }} && \
            export DB_NAME=${{ secrets.DB_NAME }} && \
            export DB_USER=${{ secrets.DB_USER }} && \
            export DB_PASSWORD='${{ secrets.DB_PASSWORD }}' && \
            docker-compose up -d"